// src/lib/header.svelte
<script lang="ts">
	import { page } from '$app/stores';
	let menuOpen = $state(false);
	function toggleMenu() {
		menuOpen = !menuOpen;
	}
</script>

<header class="py-6">
	<div class="container mx-auto flex w-full items-center justify-between px-8 md:px-14 lg:px-24">
		<a href="/" class="text-lg font-bold">ytsruh.com</a>
		<div class="hidden items-center space-x-6 md:flex xl:space-x-12">
			<a href="/" class={$page.route.id === '/' ? 'text-theme' : ''}>Home</a>
			<a href="/projects" class={$page.route.id?.includes('/projects') ? 'text-theme' : ''}>
				Projects
			</a>
			<a href="/work-history" class={$page.route.id === '/work-history' ? 'text-theme' : ''}>
				Work History
			</a>
			<a href="/blog" class={$page.route.id?.includes('/blog') ? 'text-theme' : ''}>Blog</a>
			<a href="/now" class={$page.route.id === '/now' ? 'text-theme' : ''}>Now</a>
			<a href="/contact"><button class="bg-theme px-6 py-2 font-bold">Contact me</button></a>
		</div>
		<button class="md:hidden" onclick={() => toggleMenu()} aria-label="Menu">
			<svg
				width="26"
				height="18"
				viewBox="0 0 26 18"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path
					d="M13 17.5H0.25V14.6667H13V17.5ZM25.75 10.4167H0.25V7.58333H25.75V10.4167ZM25.75 3.33333H13V0.5H25.75V3.33333Z"
					fill="white"
				/>
			</svg>
		</button>
	</div>
	{#if menuOpen === true}
		<div>
			<ul class="py-3 text-center">
				<li class="my-2 text-lg">
					<a href="/" class={$page.route.id === '/' ? 'text-theme' : ''}>Home</a>
				</li>
				<li class="my-2 text-lg">
					<a href="/projects" class={$page.route.id?.includes('/projects') ? 'text-theme' : ''}>
						Projects
					</a>
				</li>
				<li class="my-2 text-lg">
					<a href="/work-history" class={$page.route.id === '/work-history' ? 'text-theme' : ''}>
						Work History
					</a>
				</li>
				<li class="my-2 text-lg">
					<a
						href="https://ytsruh.hashnode.dev/"
						class={$page.route.id?.includes('/blog') ? 'text-theme' : ''}
					>
						Blog
					</a>
				</li>
				<li class="my-2 text-lg">
					<a href="/now" class={$page.route.id === '/now' ? 'text-theme' : ''}>Now</a>
				</li>
				<li class="my-2 text-lg">
					<a href="/contact" class={$page.route.id === '/contact' ? 'text-theme' : ''}>Contact me</a
					>
				</li>
			</ul>
		</div>
	{/if}
</header>

// app/components/Header.tsx

import { Link, useLocation } from "react-router";
import { useState } from "react";

export default function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const location = useLocation();

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <header className="py-6">
      <div className="container mx-auto flex w-full items-center justify-between px-8 md:px-14 lg:px-24">
        <Link to="/" className="text-lg font-bold">ytsruh.com</Link>
        <div className="hidden items-center space-x-6 md:flex xl:space-x-12">
          <Link to="/" className={location.pathname === '/' ? 'text-theme' : ''}>Home</Link>
          <Link to="/projects" className={location.pathname.includes('/projects') ? 'text-theme' : ''}>
            Projects
          </Link>
          <Link to="/work-history" className={location.pathname === '/work-history' ? 'text-theme' : ''}>
            Work History
          </Link>
          <Link to="/blog" className={location.pathname.includes('/blog') ? 'text-theme' : ''}>Blog</Link>
          <Link to="/now" className={location.pathname === '/now' ? 'text-theme' : ''}>Now</Link>
          <Link to="/contact"><button className="bg-theme px-6 py-2 font-bold">Contact me</button></Link>
        </div>
        <button className="md:hidden" onClick={toggleMenu} aria-label="Menu">
          <svg
            width="26"
            height="18"
            viewBox="0 0 26 18"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M13 17.5H0.25V14.6667H13V17.5ZM25.75 10.4167H0.25V7.58333H25.75V10.4167ZM25.75 3.33333H13V0.5H25.75V3.33333Z"
              fill="white"
            />
          </svg>
        </button>
      </div>
      {menuOpen && (
        <div>
          <ul className="py-3 text-center">
            <li className="my-2 text-lg">
              <Link to="/" className={location.pathname === '/' ? 'text-theme' : ''}>Home</Link>
            </li>
            <li className="my-2 text-lg">
              <Link to="/projects" className={location.pathname.includes('/projects') ? 'text-theme' : ''}>
                Projects
              </Link>
            </li>
            <li className="my-2 text-lg">
              <Link to="/work-history" className={location.pathname === '/work-history' ? 'text-theme' : ''}>
                Work History
              </Link>
            </li>
            <li className="my-2 text-lg">
              <Link to="/blog" className={location.pathname.includes('/blog') ? 'text-theme' : ''}>
                Blog
              </Link>
            </li>
            <li className="my-2 text-lg">
              <Link to="/now" className={location.pathname === '/now' ? 'text-theme' : ''}>Now</Link>
            </li>
            <li className="my-2 text-lg">
              <Link to="/contact" className={location.pathname === '/contact' ? 'text-theme' : ''}>Contact me</Link>
            </li>
          </ul>
        </div>
      )}
    </header>
  );
}
