// app/routes/contact.tsx
import ContactIcons from "~/components/ContactIcons";
import PageTitle from "~/components/PageTitle";

export default function Contact() {
  return (
    <section className="w-full">
      <PageTitle
        title="Contact"
        description="Feel free to to contact me through any of the below methods."
      />
      <ContactIcons />
    </section>
  );
}

// src/routes/contact/+page.svelte
<script lang="ts">
	import Pagetitle from '@lib/pagetitle.svelte';
	import ContactIcons from '@lib/contacticons.svelte';
</script>

<svelte:head>
	<title>Contact | ytsruh.com</title>
	<meta
		name="description"
		content="Feel free to to contact me through email, LinkedIn, Twitter/X or Github"
	/>
</svelte:head>

<section class="w-full">
	<Pagetitle
		title="Contact"
		description="Feel free to to contact me through any of the below methods."
	/>
	<ContactIcons />
</section>
