// src/routes/now.svelte
<script context="module">
  // Since there's no dynamic data here, we can prerender
  // it so that it gets served as a static asset in prod
  export const prerender = true;
  import FaCheck from "svelte-icons/fa/FaCheck.svelte";
  import FaTag from "svelte-icons/fa/FaTag.svelte";
  import FaTasks from "svelte-icons/fa/FaTasks.svelte";
  import FaTools from "svelte-icons/fa/FaTools.svelte";
  import PageTitle from "$lib/PageTitle.svelte";
  const introText =
    "A now page. An overview of whats going on right now and what are the plans for the year.";
</script>

<svelte:head>
  <title>Now | ytsruh.com</title>
  <meta
    name="description"
    content="A now page. An overview of whats going on right now and what are the plans for the year."
  />
</svelte:head>

<div class="container flex mt-20 lg:mt-36 mx-auto px-8 md:px-14 lg:px-24 w-full">
  <section class="w-full">
    <PageTitle title="Now" intro={introText} />
    <div class="grid grid-cols-1 md:grid-cols-2 gap-2 py-2 md:py-5">
      <div class="py-5 md:py-0">
        <h2 class="secondary-title">Now</h2>
        <ul class="space-y-4 py-2">
          <li class="flex items-center">
            <div class="icon mr-5"><FaTag /></div>
            <p>Working as LSEG</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaTag /></div>
            <p>Building my Machine Learning Skills</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaTag /></div>
            <p>Rennovating property</p>
          </li>
        </ul>
      </div>
      <div class="py-5 md:py-0">
        <h2 class="secondary-title">2022 Goals</h2>
        <ul class="space-y-4 py-2">
          <li class="flex items-center">
            <div class="icon mr-5"><FaCheck /></div>
            <p>Build a Svelte/Kit app</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaCheck /></div>
            <p>Build v1 of DevHub</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaCheck /></div>
            <p>Update Portfolio</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaCheck /></div>
            <p>Complete a TailwindCSS course</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaCheck /></div>
            <p>Use TailwindCSS for Homeflix</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaCheck /></div>
            <p>Build iPhone app for Homeflix</p>
          </li>
          <li class="flex items-center">
            <div class="icon mr-5"><FaCheck /></div>
            <p>Build app using Tensorflow.js or Brain.js</p>
          </li>
        </ul>
      </div>
    </div>
    <div>
      <p class="text-lg py-5">
        What is a now page? Click <a class="text-secondary" href="https://nownownow.com/about">here</a> to find
        out.
      </p>
    </div>
  </section>
</div>

<style>
  .icon {
    color: white;
    width: 24px;
    height: 24px;
  }
</style>

// app/routes/now.tsx
import type { Route } from "./+types/now";
import PageTitle from "~/components/PageTitle";
import { Tag } from "lucide-react";

export function meta({}: Route.MetaArgs) {
  return [
    {
      title: "Chris Hurst | Now Page",
      description:
        "A page that shows what I'm currently working on and what my plans are for the year.",
    },
  ];
}

export default function Now() {
  return (
    <section className="w-full">
      <PageTitle
        title="Now"
        description="A now page. An overview of whats going on right now and what the plans are for the year."
      />
      <ul className="space-y-4 py-5">
        <li className="flex items-center">
          <div className="icon mr-5">
            <Tag size="36" />
          </div>
          <p>
            Working at{" "}
            <a
              href="http://www.lseg.com"
              className="text-theme/75"
              target="_blank"
            >
              LSEG
            </a>{" "}
            in the digital team
          </p>
        </li>
        <li className="flex items-center">
          <div className="icon mr-5">
            <Tag size="36" />
          </div>
          <p>Improving my fitness</p>
        </li>
        <li className="flex items-center">
          <div className="icon mr-5">
            <Tag size="36" />
          </div>
          <p>Improving my Go skills</p>
        </li>
      </ul>
      <div className="grid grid-cols-1 gap-5 py-5 md:grid-cols-2 md:py-10 lg:grid-cols-3">
        <div>
          <span className="mb-1 block h-2 w-12 bg-theme"></span>
          <h2 className="text-3xl font-bold">Project</h2>
          <p className="py-2">
            My main goal in 2025 is to build out Webiliti into a viable & usable
            project. I'm also using it as an opportunity to build my TS skills
            and to solve some interesting problems in the Digital world.
          </p>
        </div>
        <div>
          <span className="mb-1 block h-2 w-12 bg-theme"></span>
          <h2 className="text-3xl font-bold">Go</h2>
          <p className="py-2">
            Building my skills in Go by building a number of small systems type
            projects such as a SSH server, a database & a number of CLI's /
            TUI's.
          </p>
        </div>
        <div>
          <span className="mb-1 block h-2 w-12 bg-theme"></span>
          <h2 className="text-3xl font-bold">Fitness</h2>
          <p className="py-2">
            My fitness goal this year is to run a 10k in under 60 minutes.
            Despite doing numerous 5k's and beeating 30 mins in 2024, I was not
            able to beat 60 mins.
          </p>
        </div>
      </div>
      <p className="py-10 text-lg">
        What is a now page? Click{" "}
        <a className="text-secondary" href="https://nownownow.com/about">
          here
        </a>{" "}
        to find out.
      </p>
    </section>
  );
}
