// src/routes/projects/index.svelte
<script context="module">
  import PageTitle from "$lib/PageTitle.svelte";
  import ProjectLink from "$lib/ProjectLink.svelte";
  import projects from "../../lib/projects.json";
  export const prerender = true;
  const introText =
    "I've worked on a number of JavaScript projects, both client & server side. I have featured some of them below to show new technologies that have been used or where a project is deployed.";
</script>

<svelte:head>
  <title>Projects | ytsruh.com</title>
  <meta name="description" content="ytsruh.com Projects Page" />
</svelte:head>

<div class="container mt-20 lg:mt-36 flex justify-between items-center mx-auto px-8 md:px-14 lg:px-24 w-full">
  <section class="w-full">
    <PageTitle title="Projects" intro={introText} />

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-24">
      {#each projects as project}
        <ProjectLink data={project} />
      {/each}
    </div>
  </section>
</div>

// app/routes/projects.tsx
import PageTitle from "~/components/PageTitle";
import Techlink from "~/components/Techlink";
import Visitlink from "~/components/Visitlink";
import { projects } from "./projects";

export default function Projects() {
  return (
    <section className="w-full">
      <PageTitle
        title="Projects"
        description="I've worked on a number of JavaScript & Go projects, both client & server side. I have featured some of them below to show new technologies that have been used or where a project is deployed."
      />
      <ul className="flex flex-col gap-5">
        {projects.map((project) => (
          <div
            key={project.id}
            className="flex w-full flex-col flex-wrap justify-center border border-nav p-16 xl:flex-row xl:flex-nowrap"
          >
            <div className="flex flex-wrap justify-center text-center md:basis-2/3 lg:block lg:text-left">
              <h3 className="text-2xl font-semibold text-white">{project.name}</h3>
              <div className="mb-8 mt-6 flex w-full flex-wrap justify-center gap-3 lg:w-auto lg:justify-start">
                {project.link && <Visitlink link={project.link.url} type={project.link.text} />}
                {project.github && <Visitlink link={project.github.url} type={project.github.text} />}
              </div>
              <div className="flex max-w-full flex-wrap items-center justify-between gap-2">
                {project.technologies.map((tech) => (
                  <Techlink key={tech} text={tech} />
                ))}
              </div>
              <p className="py-2">{project.description}</p>
            </div>
            <div className="m-6 flex md:basis-1/3 lg:mb-0">
              <img src={project.img} alt={project.name} className="w-full object-cover" />
            </div>
          </div>
        ))}
      </ul>
    </section>
  );
}
